# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [ ]:
import numpy as np


#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
print(np.__version__)

np.__config__.show()

1.21.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
x = np.array([20,30,10])
print("Memory size of an array: ",x.size * x.itemsize, "(Total number of elements in the array * memory size of each element in the arry)")

Memory size of an array:  24 (Total number of elements in the array * memory size of each element in the arry)


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
python -c "import numpy; numpy.info(numpy.add())"

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
x= np.zeros(10)
print(x)
x[4] = 1
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
x = np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
x = np.arange(10,50)
print(x)
z = x[::-1]
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
x = np.arange(0,9)
print(x)

print(x.reshape(3,3))

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
x = np.nonzero([1,2,0,0,4,0])
print(x)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
x = np.random.random(size=(3,3,3))
print(x)
print(x.size)

[[[0.17232291 0.40722389 0.38278477]
  [0.79223558 0.52622683 0.75540908]
  [0.48623169 0.2399814  0.76095856]]

 [[0.82932827 0.15783251 0.05199399]
  [0.69023282 0.33277018 0.09322393]
  [0.14006221 0.86450171 0.81325222]]

 [[0.60815938 0.97594213 0.98100045]
  [0.08282156 0.18322574 0.3886521 ]
  [0.80492828 0.01647435 0.23855129]]]
27


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
x = np.random.random(size=(10,10))
print(x)
print("Minimum value in x: ",x.min())
print("Maximum value in x: ",x.max())

[[0.38568665 0.41890569 0.02563397 0.87352016 0.68646794 0.06194749
  0.25523157 0.21224917 0.22520456 0.69217281]
 [0.53756751 0.24634577 0.63898094 0.57196099 0.76263359 0.38115975
  0.8725085  0.08843785 0.68190219 0.25269627]
 [0.29081504 0.86823773 0.13503848 0.90583223 0.22707098 0.87250329
  0.08609147 0.68251394 0.73321211 0.30463684]
 [0.5686306  0.40555675 0.00100233 0.09315845 0.18608179 0.0175246
  0.7279542  0.41443356 0.42834127 0.72006022]
 [0.31922109 0.42399047 0.4754103  0.02769593 0.09254657 0.49318241
  0.15250613 0.3246535  0.06691255 0.79717052]
 [0.0360311  0.87743622 0.11879825 0.4757361  0.78662761 0.27778943
  0.46354852 0.43210618 0.37589353 0.08651295]
 [0.11176455 0.43422212 0.07211744 0.97236514 0.94454176 0.88009586
  0.50787173 0.64723304 0.90528108 0.21753458]
 [0.82401886 0.46378817 0.18150253 0.34735206 0.69795826 0.50840999
  0.16584763 0.18329045 0.79119935 0.31849022]
 [0.34359658 0.19570377 0.97643189 0.04371994 0.88718644 0.11605088
  0.98829759 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
x = np.random.random(30)
print(x)
print(x.mean())

[0.663062   0.72938242 0.07135876 0.07739094 0.45458727 0.75831287
 0.37107658 0.33284748 0.81864583 0.86823863 0.38266947 0.85924009
 0.93650221 0.13092306 0.8166869  0.87906829 0.5863395  0.23310509
 0.4791562  0.01117058 0.10196357 0.56243216 0.01765053 0.59822766
 0.47203426 0.77627177 0.25263349 0.16149658 0.93674604 0.8314808 ]
0.5056900336696183


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
x = np.ones((5,5))
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
x = np.ones((3,3))
print(x)
print()
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
x = np.diag(1+ np.arange(4),k = -1)
print (x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
x = np.zeros((8,8), dtype= int)
x[1::2, ::2]= 1
x[::2, 1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
print (np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
x= np.array([[0,1], [1,0]])
z = np.tile(x,(4,4))
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
x = np.random.random((5,5))
xmax, xmin = x.max(), x.min()
Z= (x-xmin)/(xmax-xmin)
print(x)
print (Z)

[[0.99158727 0.88908469 0.2629055  0.72407546 0.05551689]
 [0.92749152 0.16998097 0.58589397 0.41563193 0.53731917]
 [0.01424365 0.88516109 0.67812151 0.72942203 0.75864093]
 [0.46665029 0.90049831 0.05348897 0.90882892 0.74967607]
 [0.02741442 0.83772508 0.69238314 0.5327983  0.07969614]]
[[1.         0.89512124 0.25442623 0.72628684 0.04223002]
 [0.93441841 0.15934756 0.58490209 0.4106931  0.53520124]
 [0.         0.89110669 0.67926761 0.73175735 0.76165359]
 [0.46289414 0.90679945 0.04015509 0.91532318 0.75248091]
 [0.01347609 0.84257103 0.69385984 0.53057557 0.06696979]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
x = np.arange(15).reshape((5,3))
print("x: ",x)
y = np.arange(6).reshape((3,2))
print("y:",y)
print("x.y: ",np.dot(x,y))

x:  [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
y: [[0 1]
 [2 3]
 [4 5]]
x.y:  [[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
x = np.arange(11)
x[(x >= 3) & (x <= 8)] = -1
print(x)

[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))  #9

from numpy import *
print(sum(range(5),-1))   #10
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z = np.arange(3) 
print(Z ** Z) # = [0^0, 1^1, 2^2] = [1, 1, 4]
print(2 << Z >> 2) #  [0, 1, 2]
print(Z < - Z) # = [False, False, False]
print(1j * Z) # = [0 + 0.j, 0 + 1.j, 0 + 2.j]
print(Z / 1 / 1)  = [0, 1, 2]
print(Z < Z > Z) #ValueError

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0) #Error
np.array(0) // np.array(0) #0
np.array([np.nan]).astype(int).astype(float) #array([-9.22337204e+18])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
x = np.random.uniform(-10, +10, 10)
np.copysign(np.ceil(np.abs(x)), x)

array([-10.,   5.,   6.,   5.,   1.,  10.,  -9.,   9.,   8.,  -3.])

#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
x = np.random.randint(0,10,10)
y = np.random.randint(0,10,10)
print(np.intersect1d(x,y))

[0 3 4]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [ ]:
#Way 1:
chk = np.seterr(all="ignore")
x = np.ones(1) / 0

# Way 2
with np.errstate(all="ignore"):
    np.arange(3) / 0

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
today     = np.datetime64('today')
yesterday = today - np.timedelta64(1)
tomorrow  = today + np.timedelta64(1)
print("Yesterday:",yesterday,"  Today:",today,"   Tomorrow:",tomorrow)

Yesterday: 2022-04-10   Today: 2022-04-11    Tomorrow: 2022-04-12


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
x = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(x)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[4. 8. 4. 2. 1. 0. 8. 2. 7. 8.]
[4. 8. 4. 2. 1. 0. 8. 2. 7. 8.]
[4. 8. 4. 2. 1. 0. 8. 2. 7. 8.]
[4 8 4 2 1 0 8 2 7 8]
[4. 8. 4. 2. 1. 0. 8. 2. 7. 8.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
x = np.zeros((5,5))
x += np.arange(5)
print(x)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
x = np.linspace(start=0, stop=1, num=11, endpoint=False)[1:]
print(x)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
x = np.random.random(10)
x.sort()
print(x)

[0.22612461 0.23517461 0.3035002  0.39439234 0.46619839 0.54661193
 0.63098588 0.81872398 0.8353581  0.97343077]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
Z = np.arange(10)
np.add.reduce(Z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
np.array_equal(A, B)

False

#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [ ]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [ ]:
Z = np.random.random((10, 2))
X, Y = Z[:, 0], Z[:, 1]
R = np.sqrt(X ** 2 + Y ** 2)
T = np.arctan2(Y, X)
print(R)
print(T)

[0.96006888 0.53740106 0.53896184 0.73773978 0.8328548  1.29720346
 0.84619627 0.92121969 0.48042575 0.2236471 ]
[1.37229984 0.40901532 1.00398871 0.82825094 1.54535099 0.83286097
 1.37002012 0.84577508 0.04926629 0.72641747]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
x = np.random.random(10)
print(x)
x[x.argmax()] = 0
print(x)

[0.35819433 0.31374922 0.47125198 0.02698236 0.19466033 0.58136535
 0.83398362 0.95542914 0.31371423 0.60495295]
[0.35819433 0.31374922 0.47125198 0.02698236 0.19466033 0.58136535
 0.83398362 0.         0.31371423 0.60495295]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [ ]:
z = np.zeros((5, 5), [('x', float), ('y', float)])
print(z)
z['x'], z['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
print("\n",z)

[[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]]

 [[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [ ]:
x = np.random.random((5, 5))
y = np.random.random((5, 5))
c = 1.0 / np.subtract.outer(x, y)
print(np.linalg.det(c))

[[-2.31097973e+03  2.71468894e+03 -5.81641258e+04 -2.26840273e+04
   5.69290401e+03]
 [-5.24141085e+04 -1.52598393e+03 -4.33177439e+07 -7.50078192e+08
  -2.36482959e+05]
 [-6.96367106e+06 -9.48750008e+04 -1.44785626e+07  3.53673557e+07
  -3.19475599e+06]
 [-2.68627976e+06  6.57199567e+03  8.49443745e+08 -5.45555017e+06
  -2.95633735e+02]
 [ 1.05965522e+05  1.30789265e+04  3.55650515e+04 -6.23304937e+05
  -2.89819820e+04]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
np.set_printoptions(threshold=float("inf"))
x = np.zeros((40,40))
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
x = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(x-v)).argmin()
print(x[index])

11


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [ ]:
Z = np.zeros(10, [ ('position', [ ('x', float),
                                  ('y', float)]),
                   ('color',    [ ('r', float),
                                  ('g', float),
                                  ('b', float)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [ ]:
x = np.random.random((10,2))
#print(x)
i,j = np.atleast_2d(x[:,0], x[:,1])
D = np.sqrt( (i-i.T)**2 + (j-j.T)**2)
print(D)

[[0.         0.81543363 0.42781388 1.04105098 0.70113906 0.57787249
  0.32424337 0.71159479 0.90860815 0.67841624]
 [0.81543363 0.         0.97229596 0.32874908 0.13077224 0.89430564
  0.63971423 0.9025173  0.30354172 0.49393244]
 [0.42781388 0.97229596 0.         1.07703818 0.89886325 0.23019559
  0.33729236 0.37658905 0.92537116 0.60020692]
 [1.04105098 0.32874908 1.07703818 0.         0.44857932 0.93246588
  0.78534954 0.8872601  0.15212313 0.48693179]
 [0.70113906 0.13077224 0.89886325 0.44857932 0.         0.84938929
  0.56167463 0.87864649 0.39299483 0.49510205]
 [0.57787249 0.89430564 0.23019559 0.93246588 0.84938929 0.
  0.3424795  0.14818807 0.78138561 0.4459174 ]
 [0.32424337 0.63971423 0.33729236 0.78534954 0.56167463 0.3424795
  0.         0.44011634 0.63935472 0.36306007]
 [0.71159479 0.9025173  0.37658905 0.8872601  0.87864649 0.14818807
  0.44011634 0.         0.74140033 0.41791206]
 [0.90860815 0.30354172 0.92537116 0.15212313 0.39299483 0.78138561
  0.63935472 0.741400

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
x = (np.random.rand(10)*100).astype(np.float32)
y = x.view(np.int32)
y[:] = x
print(y)

[17 21 35 93  7 60 12 63 37 88]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')
f = np.genfromtxt(s, delimiter=",", dtype=int)
print(f)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [ ]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [ ]:
x,y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(x*x + y*y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [ ]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [ ]:
x = np.random.rand(5, 10)

y = x - x.mean(axis=1, keepdims=True)

print(y)

[[-0.29018786  0.12352954 -0.29631135  0.42001683  0.00340793  0.14475507
   0.50448203 -0.28176418 -0.04732796 -0.28060007]
 [-0.09242434 -0.03112762 -0.12202113 -0.27307577 -0.36296632  0.37858587
   0.12681641  0.30932266 -0.24170208  0.30859232]
 [-0.25140279  0.15242626 -0.17808241 -0.11692483  0.07060941  0.27232132
  -0.30020652  0.14384817 -0.11735971  0.3247711 ]
 [ 0.19689912  0.33643822 -0.2862382  -0.32750313  0.41975301 -0.01063328
  -0.37481258  0.12838055  0.17349607 -0.25577977]
 [ 0.11036912  0.25433703  0.39068999 -0.08312307  0.04317853 -0.23452545
   0.45238657 -0.22713505 -0.44365204 -0.26252563]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [ ]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])


[[9 2 2]
 [3 7 4]
 [8 3 9]]
[[9 2 2]
 [8 3 9]
 [3 7 4]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [ ]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [ ]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.4429125255403874


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [ ]:
x = np.arange(3).reshape(3,1)
#print(x)
y = np.arange(3).reshape(1,3)
#print(y)

it = np.nditer([x,y,None])
for i,j,k in it: 
  k[...] = i + j
print(it.operands[2])

[[0]
 [1]
 [2]]
[[0 1 2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [ ]:
z = np.ones(10)
y = np.random.randint(0,len(z),20)
z += np.bincount(y, minlength=len(z))
print(z)

x = np.ones(10)
i = np.random.randint(0,len(x),20)
np.add.at(x, i, 1)
print(x)

[3. 2. 2. 3. 7. 3. 1. 3. 2. 4.]
[4. 3. 1. 6. 1. 1. 3. 7. 2. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [ ]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [ ]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [ ]:
x = np.random.randint(0,10,(3,4,3,4))
sum = x.sum(axis=(-2,-1))
print(sum)

[[49 53 34 61]
 [59 38 43 65]
 [49 56 53 68]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [ ]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.40431498 0.5069399  0.41426765 0.37070833 0.40361595 0.60968587
 0.40860719 0.48751549 0.65980799 0.45837835]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [ ]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

np.diag(np.dot(A, B))


array([1.20194577, 0.78071675, 0.51072794, 0.63414434, 1.22709475])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [ ]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [ ]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [ ]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [ ]:
faces = np.random.randint(0,100,(10,3))
f = np.roll(faces.repeat(2,axis=1),-1,axis=1)
f = f.reshape(len(f)*3,2)
f = np.sort(f,axis=1)
g = f.view( dtype=[('p0',f.dtype),('p1',f.dtype)] )
g = np.unique(g)
print(g)

[( 7, 18) ( 7, 99) (15, 70) (15, 86) (17, 27) (17, 52) (17, 56) (17, 70)
 (18, 99) (21, 23) (21, 76) (23, 47) (23, 60) (23, 76) (27, 52) (30, 94)
 (30, 97) (41, 72) (41, 83) (47, 53) (47, 60) (47, 81) (53, 81) (56, 70)
 (70, 86) (72, 83) (79, 89) (79, 97) (89, 97) (94, 97)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [ ]:
from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(20)
print(sliding_window_view(Z, window_shape=3).mean(axis=-1))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [ ]:
from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(10)
print(Z)
print(sliding_window_view(Z, window_shape=3))

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [ ]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 6.76625146e-02, -6.11305217e-01,  1.64505122e-01,  4.33642468e-01,
       -2.96240871e-01, -1.50391456e-02,  6.73394947e-01, -8.96079282e-01,
        9.78327708e-01, -5.47903226e-01,  1.62703881e-01,  2.94648181e-01,
       -2.11980006e-01, -2.46031982e-01, -6.52504679e-01, -4.34698694e-01,
        2.62340302e-01,  7.03953607e-01,  7.24454434e-01, -1.53717930e-02,
       -6.32524325e-01, -8.89239861e-01, -4.84383546e-01, -6.23795269e-01,
        8.05916936e-01, -1.76619819e-01,  6.11127183e-01,  5.43143373e-01,
       -7.08971167e-01, -4.23678763e-01, -5.90854498e-01, -5.20813260e-01,
       -3.65332802e-01, -3.81012722e-01,  1.82677046e-01, -1.20287873e-01,
        5.04702100e-01,  9.09078399e-03,  4.58214191e-01,  3.40432611e-01,
       -2.29739615e-01, -7.92108906e-01, -8.58063355e-01,  9.58854742e-01,
       -4.21321796e-01,  9.02092779e-01, -3.79810489e-01,  5.05452198e-04,
       -6.96779766e-01, -2.89722381e-01,  1.28918302e-01,  5.50959397e-01,
        4.73974369e-01,  

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [ ]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 5.72780664 11.55066067  2.9802148   9.51340803  0.65070839  9.96410186
  1.7759127   1.78545409  0.92578219  9.24117205]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [ ]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[4.60295282e+00 3.49370228e+00 4.44235135e+00 1.75687140e+00
  1.60335519e+00 4.06128687e+00 1.00637377e+01 6.37113649e+00
  1.14661452e+00 4.65749503e+00]
 [2.20851033e+00 6.42005497e+00 6.79930042e+00 1.67153099e+00
  3.85093326e+00 3.81463085e+00 1.05439402e+01 7.61231571e+00
  3.30252407e+00 6.57903327e+00]
 [8.52317911e+00 3.83509465e+00 2.62140138e+00 6.87226085e-01
  5.32363979e+00 1.99652236e+00 6.35027870e+00 1.10764988e+00
  5.65635074e+00 1.79704879e+00]
 [1.01484645e+01 4.60694101e-01 2.54889191e+00 4.82881867e+00
  1.02608789e-02 7.37866208e+00 1.22079467e+01 7.09126372e+00
  2.05195542e-01 3.88775090e+00]
 [4.14881522e-01 5.97895939e+00 4.77545199e+00 2.13548421e+00
  1.64645241e+00 3.52225639e-03 6.86293891e+00 4.32793426e+00
  9.60167521e-01 3.92916796e+00]
 [6.21574096e+00 1.38192847e+01 1.14337250e+01 1.57775099e+00
  8.05227681e+00 1.29310495e-01 8.89239179e+00 8.29094318e+00
  7.15162055e+00 9.56326798e+00]
 [2.98135608e-01 8.14139803e+00 7.90508008e+00 9.78890541e

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [ ]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
from numpy.lib.stride_tricks import sliding_window_view

z = np.arange(1, 15, dtype=np.uint32)
print(sliding_window_view(z, window_shape=4))

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [ ]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [ ]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

7


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
from numpy.lib import stride_tricks

Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[3 3 1]
   [2 1 4]
   [1 4 1]]

  [[3 1 4]
   [1 4 0]
   [4 1 2]]

  [[1 4 2]
   [4 0 3]
   [1 2 2]]

  [[4 2 3]
   [0 3 4]
   [2 2 0]]

  [[2 3 3]
   [3 4 4]
   [2 0 0]]

  [[3 3 4]
   [4 4 0]
   [0 0 4]]

  [[3 4 3]
   [4 0 3]
   [0 4 4]]

  [[4 3 1]
   [0 3 0]
   [4 4 1]]]


 [[[2 1 4]
   [1 4 1]
   [0 1 3]]

  [[1 4 0]
   [4 1 2]
   [1 3 3]]

  [[4 0 3]
   [1 2 2]
   [3 3 4]]

  [[0 3 4]
   [2 2 0]
   [3 4 4]]

  [[3 4 4]
   [2 0 0]
   [4 4 4]]

  [[4 4 0]
   [0 0 4]
   [4 4 1]]

  [[4 0 3]
   [0 4 4]
   [4 1 0]]

  [[0 3 0]
   [4 4 1]
   [1 0 0]]]


 [[[1 4 1]
   [0 1 3]
   [2 0 3]]

  [[4 1 2]
   [1 3 3]
   [0 3 2]]

  [[1 2 2]
   [3 3 4]
   [3 2 0]]

  [[2 2 0]
   [3 4 4]
   [2 0 1]]

  [[2 0 0]
   [4 4 4]
   [0 1 2]]

  [[0 0 4]
   [4 4 1]
   [1 2 2]]

  [[0 4 4]
   [4 1 0]
   [2 2 3]]

  [[4 4 1]
   [1 0 0]
   [2 3 0]]]


 [[[0 1 3]
   [2 0 3]
   [4 4 0]]

  [[1 3 3]
   [0 3 2]
   [4 0 3]]

  [[3 3 4]
   [3 2 0]
   [0 3 0]]

  [[3 4 4]
   [2 0 1]
   [3 0 4]]

  [[4 4 4]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [ ]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 4 10  9 16 15]
 [10  9 13  8  1]
 [ 9 13  8 42 11]
 [16  8 42  5  1]
 [15  1 11  1  0]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [ ]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [ ]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)


[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [ ]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

#Option 1
print (Z[np.argsort(Z)[-n:]])

#Option 2
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9998 9999 9997 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [ ]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [ ]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [ ]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1 loop, best of 5: 3.75 s per loop
10 loops, best of 5: 162 ms per loop
10 loops, best of 5: 148 ms per loop


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [ ]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[1 2 3 6]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [ ]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[3 0 3]
 [1 2 2]
 [1 4 1]
 [0 3 4]
 [1 2 1]
 [2 4 0]
 [0 4 1]
 [1 4 2]
 [0 1 1]
 [1 1 0]]
[[3 0 3]
 [1 2 2]
 [1 4 1]
 [0 3 4]
 [1 2 1]
 [2 4 0]
 [0 4 1]
 [1 4 2]
 [0 1 1]
 [1 1 0]]
[[3 0 3]
 [1 2 2]
 [1 4 1]
 [0 3 4]
 [1 2 1]
 [2 4 0]
 [0 4 1]
 [1 4 2]
 [0 1 1]
 [1 1 0]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [ ]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [ ]:
Z = np.random.randint(0,2,(6,3))
print(Z)
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 1 0]
 [0 0 1]
 [1 1 1]
 [1 0 1]
 [1 0 0]
 [0 0 0]]
[[0 0 0]
 [0 0 1]
 [0 1 0]
 [1 0 0]
 [1 0 1]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [ ]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.65700416, 0.36265168, 0.39641451, 0.38272759, 0.48714281,
        0.00557724, 0.69492019, 0.21467274, 0.223272  , 0.57086507],
       [0.79260973, 0.43750294, 0.47823441, 0.46172252, 0.58768902,
        0.00672838, 0.83835163, 0.25898117, 0.26935532, 0.68869154],
       [0.6148037 , 0.33935797, 0.37095215, 0.35814437, 0.45585282,
        0.005219  , 0.65028432, 0.20088396, 0.20893087, 0.53419746],
       [0.29746436, 0.16419371, 0.17948012, 0.17328325, 0.22055815,
        0.00252514, 0.31463117, 0.09719495, 0.10108834, 0.25846413],
       [0.16983202, 0.0937435 , 0.10247101, 0.09893301, 0.12592378,
        0.00144169, 0.17963311, 0.05549174, 0.0577146 , 0.14756553],
       [0.55694331, 0.30742032, 0.33604111, 0.3244387 , 0.41295162,
        0.00472783, 0.58908478, 0.18197837, 0.18926798, 0.48392309],
       [0.28489975, 0.15725832, 0.17189905, 0.16596393, 0.21124199,
        0.00241848, 0.30134145, 0.09308953, 0.09681847, 0.24754686],
       [0.2211896 , 0.12209174, 0.1334584

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [ ]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [ ]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [ ]:
X = np.random.randn(100) # random 1D array
print(X)
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
print(idx)
means = X[idx].mean(axis=1)
print(means)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[ 0.32243631 -0.62539756  1.02299355 -1.31681035  0.6909506   1.38063549
 -0.26144872  0.09404761  1.01035645 -0.67065008  0.90660963  0.5945292
  1.20611964  1.22706367  0.0379478   0.65747806 -0.76392368  0.35584151
 -0.08132419 -0.33239843  2.22236548  1.28436987 -0.28785092  0.45556115
  1.83979538  0.0825836   0.11661067 -0.99854675 -0.2531547  -0.2957957
  0.56400372  0.61309138  1.48845088  1.37869245 -1.81673274 -1.65526463
  0.20298057 -1.04898879  0.37622328  0.63307984 -0.26155861  0.64324664
  1.34953943  0.17535741 -0.79871558 -0.73479804 -0.06962027  1.18806383
 -0.02442058  0.50688489 -0.32763824  1.2985143   0.24603353  1.10904265
  0.6230146   0.05511195 -0.07506217  0.56353724 -0.56558934 -2.0553144
  0.80336792 -2.47200517 -0.20727444 -0.44565512 -0.71091252 -0.47058526
 -1.4212485  -1.12514496  1.19398107  0.22766167 -0.57496452  0.11508896
  0.4086471  -0.42034442  0.07259263  1.10723524 -1.8024518   1.05310737
  1.80585108  0.53746852  0.15258073  0.77393156 -0.60